name: Deploy html folder to GitHub Pages

on:
  push:
    branches:
      - master  # 如果你的主分支叫 main，请改成 main

# 设置运行所需的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 保证同一时间只有一个部署任务
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html' # 👈 核心：指定只打包和上传 html 文件夹里的所有网页

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
